### ISSUE TITLE
InvalidCipherTextException: mac check in CCM failed

### ISSUE THREAD

**Issue by PJ-Kowalski** [bcgit/bc-csharp#418]
Hello,
I using DTLSNet libary with implements bc-csharp project, when client try to communicate over DTLS i receive following error: 

**InvalidCipherTextException: mac check in CCM failed**

Full text:
Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: bad_record_mac(20)
 ---> Org.BouncyCastle.Crypto.InvalidCipherTextException: mac check in CCM failed
   at Org.BouncyCastle.Crypto.Modes.CcmBlockCipher.ProcessPacket(Byte[] input, Int32 inOff, Int32 inLen, Byte[] output, Int32 outOff) in /_/crypto/src/crypto/modes/CcmBlockCipher.cs:line 336
   at Org.BouncyCastle.Crypto.Modes.CcmBlockCipher.DoFinal(Byte[] outBytes, Int32 outOff) in /_/crypto/src/crypto/modes/CcmBlockCipher.cs:line 157
   at Org.BouncyCastle.Crypto.Tls.TlsAeadCipher.DecodeCiphertext(Int64 seqNo, Byte type, Byte[] ciphertext, Int32 offset, Int32 len) in /_/crypto/src/crypto/tls/TlsAeadCipher.cs:line 219
   --- End of inner exception stack trace ---
   at Org.BouncyCastle.Crypto.Tls.TlsAeadCipher.DecodeCiphertext(Int64 seqNo, Byte type, Byte[] ciphertext, Int32 offset, Int32 len) in /_/crypto/src/crypto/tls/TlsAeadCipher.cs:line 223
   at DTLS.ServerHandshake.ProcessHandshake(DTLSRecord record) in D:\Repos\DTLS\ServerHandshake.cs:line 92
   at DTLS.Server.ProcessRecord(SocketAddress address, Session session, DTLSRecord record) in D:\Repos\DTLS\Server.cs:line 338

error occurs  when this line is executed: 
`data = session.Cipher.DecodeCiphertext(sequenceNumber, (byte)TRecordType.Handshake, record.Fragment, 0, record.Fragment.Length);`

Values passed to method are following:
Epoch : 1, Sequence number: 281474976710656,  Record :22, Cipher: Org.BouncyCastle.Crypto.Tls.TlsAeadCipher

I will be grate full for any advice, how to solve issue

**Comment by peterdettman** [comment]
That would be a natural error to see in case of a corrupted/modified packet. Is it happening immediately (and reproducibly) or is it something that happens occasionally after some initial packet exchange?

There is a property on TlsPeer (so available to both TlsClient and TlsServer) that can be overridden to ignore this type of error and continue the connection: IgnoreCorruptDtlsRecords . I don't know anything about DTLSNet, but perhaps it can be modified to expose that setting.

**Comment by PJ-Kowalski** [comment]
It is happening always, for different devices
![wiresharkDTLS](https://user-images.githubusercontent.com/78762258/219313777-bfabbdf2-af3e-4699-9496-7124b5679569.png)
And communication is not continued
Devices ar connected via router (different geographical location)
