### ISSUE TITLE
Current commit (efb5751f) tests fail, failure introduced in f6ff879, works in 41a48c2.

### ISSUE THREAD

**Issue by kyanha** [bcgit/bc-csharp#55]
[...all ASN.1 tests and all Pgp tests before this pass...]
PgpECMessageTest: Okay
PgpParsingTest: Okay
Tests failed with exception: Object reference not set to an instance of an object.
   at NUnit.Core.TestSuite.RunAllTests(TestResult suiteResult, EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuite(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuiteInContext(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.Run(EventListener listener, ITestFilter filter)
   at Org.BouncyCastle.Bcpg.OpenPgp.Examples.Tests.AllTests.Main(String[] args) in C:\work\bcgit\bc-csharp\crypto\test\src\openpgp\examples\test\AllTests.cs:line 423
   at crypto_test.CryptoTest.Main(String[] args) in C:\work\bcgit\bc-csharp\crypto-test\CryptoTest.cs:line 20
Done in 46923ms.

This occurs in both Debug and Release configurations.  Due to circular dependencies, I'm unable to compile a version of nunit that has debugging information enabled to provide better insight as to what's going on.

**Comment by kyanha** [comment]
This occurs also with commit f6ff879, the first version with nUnit 2.6.4.

That revision's parent commit 51a48c2 works correctly.

I am using Visual Studio 2015 Community, if that helps?

**Comment by kyanha** [comment]
I get this error (NullReferenceException inside NUnit 2.6.4) in the following classes:

Org.BouncyCastle.Bcpg.OpenPgp.Examples.Tests.AllTests
Org.BouncyCastle.Cms.Tests.AllTests
Org.BouncyCastle.Crypto.Agreement.Tests.AllTests
Org.BouncyCastle.Crypto.IO.Tests.AllTests
Org.BouncyCastle.Math.Tests.AllTests
Org.BouncyCastle.Math.EC.Tests.AllTests
Org.BouncyCastle.Ocsp.Tests.AllTests
Org.BouncyCastle.Tsp.Tests.AllTests

**Comment by kyanha** [comment]
All of these errors occur with NUnit 3.2.0, as well.  (NUnit 3 removed the SuiteAttribute, so requires the removal of all [Suite] annotations on upgrade.)

**Comment by kyanha** [comment]
All individual tests pass with NUnit 3.2's nunit3-console.exe, including the tests from those classes.
